repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
        exclude: '^docs'
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/biomejs/pre-commit
    rev: v0.1.0
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.4.1"]
        files: '^docs'

  - repo: local
    hooks:
      #Use dotnet format already installed on your machine
      - id: dotnet-format
        stages: [commit] # Default, runs only on commit, not on push
        name: dotnet-format
        language: system
        entry: bash -c 'cd backend && dotnet format'
        types_or: ["c#"]
