name: 🎉 Release Please
on:
  push:
    branches:
      - main

jobs:
  release_please:
    name: 🔖 Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Create Release PR
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          bump-minor-pre-major: true
          changelog-types: >
            [{"type":"build", "section":"📦 Build system","hidden":false},
            {"type":"chore", "section":"🧹 Chores","hidden":false},
            {"type":"ci", "section":"👷 CI/CD","hidden":false},
            {"type":"docs","section":"📚 Documentation","hidden":false},
            {"type":"feat","section":"✨ Features","hidden":false},
            {"type":"fix","section":"🐛 Bug Fixes","hidden":false},
            {"type":"perf", "section":"🏎️ Performance","hidden":false},
            {"type":"refactor", "section":"🔨 Refactor","hidden":false},
            {"type":"revert", "section":"⏪️ Revert","hidden":false},
            {"type":"style","section":"💎 Style","hidden":false},
            {"type":"test", "section":"🧪 Tests","hidden":false}]
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
