name: 🎉 Release Please
on:
  push:
    branches:
      - main

jobs:
  release_please:
    name: 🔖 Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Create Release PR
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
